---
- name: Check if Swarm has already been Initialized
  shell: docker node ls
  register: swarm_status
  ignore_errors: true

# - name: leave from swarm
#   shell: >
#     docker swarm leave -f


- name: Initialize Docker Swarm
  block:
    #1
    - name: Initialize Docker Swarm on first node
      shell: >
        docker swarm init
        --advertise-addr={{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:2377
    #2
    - name: Get the Manager join-token
      shell: docker swarm join-token --quiet manager
      register: manager_token

    - name: Print managers
      debug:
        msg: "{{ manager_token }}"
    #3
    - name: Get the worker join-token
      shell: docker swarm join-token --quiet worker
      register: worker_token

    - name: Print worker
      debug:
        msg: "{{ worker_token }}"
  when: 
    - swarm_status.rc != 0
    - inventory_hostname in groups['swarm-manager']