---
- name: Check if Swarm is Already Initialized
  shell: docker node ls
  register: swarm_status
  ignore_errors: true

- name: Add Workers to the Swarm
  shell: "docker swarm join --token {{ hostvars[groups['swarm-manager']]['worker_token']['stdout'] }} {{ hostvars[groups['swarm-manager']]['ansible_default_ipv4']['address'] }}:2377"
  ignore_errors: yes
  with_items:
  - "{{ groups['docker_swarm_worker'] }}"
  when: 
    - inventory_hostname in groups['swarm-manager']

- name: Test
  debug:
    msg: "{{ hostvars[groups['swarm-manager']]['worker_token']['stdout'] }}"
  when:
    - inventory_hostname in groups['swarm-manager']
  ignore_errors: yes


- name: Test2
  debug:
    msg: "{{ groups['swarm-manager'][0]['worker_token']['stdout'] }}"
  when:
    - inventory_hostname in groups['swarm-manager']
  ignore_errors: yes

- name: Test3
  debug:
    msg: "{{ groups['swarm-manager']}}"
  when:
    - inventory_hostname in groups['swarm-manager']
  ignore_errors: yes

- name: Test4
  debug:
    msg: "{{ hostvars['192.168.56.107']['worker_token'] }}"
  when:
    - inventory_hostname in groups['swarm-manager']
  ignore_errors: yes

- name: Test4
  debug:
    msg: "{{ hostvars[inventory_hostname].item}}"
  with_items:
    - groups['swarm-manager']
  when:
    - inventory_hostname in groups['swarm-manager']
  ignore_errors: yes

  # inventory_hostname
  # hostvars[inventory_hostname].ansible_host