---
- name: Check if Swarm is Already Initialized
  shell: docker node ls
  register: swarm_status
  ignore_errors: true

- name: Add Workers to the Swarm
  block:
    - name: ADD workers to masters nodes
      shell: "docker swarm join --token {{ hostvars[item]['worker_token']['stdout'] }} {{ hostvars[item]['ansible_enp0s8']['ipv4']['address'] }}:2377"
      ignore_errors: yes
      with_items:
        - "{{ hostvars[inventory_hostname]['groups']['swarm-manager'] }}"
  when: 
    - inventory_hostname in groups['docker_swarm_worker']

# - name: Add Workers to the Swarm
#   shell: "docker swarm join --token {{ hostvars[item]['groups']['swarm-manager']['worker_token']['stdout'] }} {{ hostvars[item]['ansible_enp0s8']['ipv4']['address'] }}:2377"
#   ignore_errors: yes
#   with_items:
#     - "{{ hostvars[inventory_hostname]['groups']['docker_swarm_worker'] }}"
#   when: 
#     - inventory_hostname in groups['docker_swarm_worker']

# - name: Show me all parameters workers 2
#   debug:
#     msg: "{{ hostvars[item]['ansible_enp0s8']['ipv4']['address'] }}"
#   with_items:
#    - "{{ hostvars[inventory_hostname]['groups']['swarm-manager'] }}"
#   when:
#     - inventory_hostname in groups['docker_swarm_worker']

# - name: Test
#   debug:
#     msg: "{{ hostvars[groups['swarm-manager']]['worker_token']['stdout'] }}"
#   when:
#     - inventory_hostname in groups['swarm-manager']
#   ignore_errors: yes


# - name: Test2
#   debug:
#     msg: "{{ groups['swarm-manager'][0]['worker_token']['stdout'] }}"
#   when:
#     - inventory_hostname in groups['swarm-manager']
#   ignore_errors: yes

# - name: Test3
#   debug:
#     msg: "{{ groups['swarm-manager']}}"
#   when:
#     - inventory_hostname in groups['swarm-manager']
#   ignore_errors: yes

# - name: Test4
#   debug:
#     msg: "{{ hostvars['192.168.56.107']['worker_token'] }}"
#   when:
#     - inventory_hostname in groups['swarm-manager']
#   ignore_errors: yes

# - name: Test4
#   debug:
#     msg: "{{ hostvars[inventory_hostname]}}"
#   # with_items:
#   #   - groups['swarm-manager']
#   when:
#     - inventory_hostname in groups['swarm-manager']
#   ignore_errors: yes

# - name: Test5
#   debug:
#     msg: "{{ hostvars[item]['ansible_default_ipv4']['address']}}"
#   with_items:
#     - groups['swarm-manager']
#   when:
#     - inventory_hostname in groups['docker_swarm_worker']
#   ignore_errors: yes

# - name: Setting host facts using key=value pairs, note that this always creates strings or booleans
#   set_fact: 
#     token: "{{ hostvars[inventory_hostname]['worker_token']['stdout'] }}"
#     host: "{{ hostvars[inventory_hostname][ansible_enp0s8][ipv4.address] }}"
#   when:
#     - inventory_hostname in groups['swarm-manager']

# - name: set fact 3
#   set_fact: hostname="{{ hostvars[inventory_hostname]['worker_token']['stdout'] }}"


# - name: Setting host facts using complex arguments
#   set_fact: one_fact: something

# - name: Setting host facts using complex arguments
#   set_fact: hostname: "{{ hostvars[inventory_hostname]['worker_token']['stdout'] }}"
#   when:
#     - inventory_hostname in groups['swarm-manager'] 
    # {{ hostvars[inventory_hostname]['worker_token']['stdout'] }}

# - name: Test88
#   debug:
#     var: host
#   when:
#     - inventory_hostname in groups['swarm-manager']

# # "hostname": "SWMTKN-1


# - name: Add Workers to the Swarm
#   shell: "docker swarm join --token {{ hostvars[host]['worker_token']['stdout'] }} {{ hostvars[host]['ansible_default_ipv4']['address'] }}:2377"
#   ignore_errors: yes
#   when: 
#     - inventory_hostname in groups['docker_swarm_worker']



# - name: Test6
#   debug:
#     msg: "{{ hostvars[item]['ansible_default_ipv4']['address']}}"
#   with_items:
#     - groups['swarm-manager']
#   when:
#     - inventory_hostname in groups['docker_swarm_worker']
#   ignore_errors: yes
  # inventory_hostname
  # hostvars[inventory_hostname].ansible_host
  # {{ hostvars['your_host_group'].ansible_host }}
  # hostvars[inventory_hostname]