---
- name: Check if Swarm is Already Initialized
  shell: docker node ls
  register: swarm_status
  ignore_errors: true

- name: Add Workers to the Swarm
  shell: "docker swarm join --token {{ hostvars['groups['docker_swarm_master']']['worker_token']['stdout'] }} {{ hostvars[groups['docker_swarm_master']]['ansible_default_ipv4']['address'] }}:2377"
  ignore_errors: yes
  with_items:
  - "{{ groups['docker_swarm_master'] }}"
  when: 
    - swarm_status.rc != 0
    - inventory_hostname in groups['docker_swarm_worker']