# ---
# - name: Show me all parameters
#   debug:
#     msg: "{{ item }}"
#   with_items:
#    - "{{ hostvars[inventory_hostname]['groups']['docker_swarm_worker'] }}"
#   when:
#     - inventory_hostname in groups['swarm-manager']


#     # hostvars[inventory_hostname]

# - name: Show me all parameters workers
#   debug:
#     msg: "{{ hostvars[item]['groups'] }}"
#   with_items:
#    - "{{ hostvars[inventory_hostname]['groups']['swarm-manager'] }}"
#   when:
#     - inventory_hostname in groups['docker_swarm_worker']




# - name: Show me all parameters workers 2
#   debug:
#     msg: "{{ hostvars[item]['ansible_enp0s8']['ipv4']['address'] }}"
#   with_items:
#    - "{{ hostvars[inventory_hostname]['groups']['swarm-manager'] }}"
#   when:
#     - inventory_hostname in groups['docker_swarm_worker']


- name: Test localhost
  shell: pwd
  delegate_to: localhost
  register: test

- name: Test
  debug:
    msg: "{{test}}"

- name: Send docker daemon json configuration to nodes, hub, nexus, bash sh script
  template:
    src: templates/{{ item.src }}.j2
    dest: "{{item.dest}}{{ item.src }}" 
    owner: root
    group: root
    mode: 0755
  delegate_to: localhost
  with_items:
    - {src: "create-self-certs.sh", dest: "~/"}

- name: Change the working directory to /root/.docker/ before executing the command and Run a script only if /root/.docker/ca.pem does not exist on the remote node
  shell: >
    ~/create-self-certs.sh >> somelog.txt
  delegate_to: localhost
  ignore_errors: true